"""add_organization_features_table

Revision ID: 0c3d8f320f1a
Revises: 3d503719dc43
Create Date: 2025-11-21 20:48:27.773742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c3d8f320f1a'
down_revision = '3d503719dc43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    
    # Check if organization_features table exists
    result = conn.execute(text("SHOW TABLES LIKE 'organization_features'"))
    table_exists = result.fetchone() is not None
    
    if not table_exists:
        op.create_table('organization_features',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('organization_id', sa.Integer(), nullable=False),
            sa.Column('feature_name', sa.String(length=50), nullable=False),
            sa.Column('enabled', sa.Boolean(), nullable=False, server_default='1'),
            sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_organization_features_organization_id'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('organization_id', 'feature_name', name='uq_organization_features_org_feature')
        )
        op.create_index('ix_organization_features_feature_name', 'organization_features', ['feature_name'], unique=False)
        op.create_index('ix_organization_features_organization_id', 'organization_features', ['organization_id'], unique=False)
    op.alter_column('data_cache', 'payload',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index('uq_organization_invitations_token', table_name='organization_invitations')
    op.create_index(op.f('ix_organization_invitations_id'), 'organization_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.drop_index('key', table_name='platform_settings')
    op.create_index(op.f('ix_platform_settings_id'), 'platform_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_features_id'), 'user_features', ['id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.drop_index(op.f('ix_user_features_id'), table_name='user_features')
    op.drop_index(op.f('ix_platform_settings_id'), table_name='platform_settings')
    op.create_index('key', 'platform_settings', ['key'], unique=True)
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_invitations_id'), table_name='organization_invitations')
    op.create_index('uq_organization_invitations_token', 'organization_invitations', ['token'], unique=True)
    op.alter_column('data_cache', 'payload',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_index(op.f('ix_organization_features_organization_id'), table_name='organization_features')
    op.drop_index(op.f('ix_organization_features_id'), table_name='organization_features')
    op.drop_index(op.f('ix_organization_features_feature_name'), table_name='organization_features')
    op.drop_table('organization_features')
    # ### end Alembic commands ###

