"""add_telegram_users_table

Revision ID: 4b8530710f48
Revises: adc7809d520e
Create Date: 2025-11-12 00:16:03.550548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b8530710f48'
down_revision = 'adc7809d520e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_users_chat_id'), 'telegram_users', ['chat_id'], unique=True)
    op.create_index(op.f('ix_telegram_users_id'), 'telegram_users', ['id'], unique=False)
    op.alter_column('app_settings', 'is_secret',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('available_data_sources', 'supports_crypto',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('available_data_sources', 'supports_stocks',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('available_data_sources', 'supports_forex',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # Skip payload column change - already MEDIUMTEXT from previous migration
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_cache', 'payload',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('available_data_sources', 'supports_forex',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('available_data_sources', 'supports_stocks',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('available_data_sources', 'supports_crypto',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('app_settings', 'is_secret',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_index(op.f('ix_telegram_users_id'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_chat_id'), table_name='telegram_users')
    op.drop_table('telegram_users')
    # ### end Alembic commands ###

