"""add_rag_tables

Revision ID: 7216daacb1a8
Revises: a1b2c3d4e5f6
Create Date: 2025-11-25 22:08:16.312352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7216daacb1a8'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vector_db_type', sa.String(length=50), nullable=False, server_default='chromadb'),
    sa.Column('embedding_model', sa.String(length=255), nullable=False, server_default='openai/text-embedding-3-small'),
    sa.Column('document_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_knowledge_bases_id'), 'rag_knowledge_bases', ['id'], unique=False)
    op.create_index(op.f('ix_rag_knowledge_bases_organization_id'), 'rag_knowledge_bases', ['organization_id'], unique=False)
    op.create_table('rag_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rag_id'], ['rag_knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rag_id', 'user_id', name='uq_rag_access_rag_user')
    )
    op.create_index(op.f('ix_rag_access_id'), 'rag_access', ['id'], unique=False)
    op.create_index(op.f('ix_rag_access_rag_id'), 'rag_access', ['rag_id'], unique=False)
    op.create_index(op.f('ix_rag_access_user_id'), 'rag_access', ['user_id'], unique=False)
    op.create_table('rag_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rag_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('embedding_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='embeddingstatus'), nullable=False, server_default='pending'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rag_id'], ['rag_knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_documents_id'), 'rag_documents', ['id'], unique=False)
    op.create_index(op.f('ix_rag_documents_rag_id'), 'rag_documents', ['rag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_documents_rag_id'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_id'), table_name='rag_documents')
    op.drop_table('rag_documents')
    op.drop_index(op.f('ix_rag_access_user_id'), table_name='rag_access')
    op.drop_index(op.f('ix_rag_access_rag_id'), table_name='rag_access')
    op.drop_index(op.f('ix_rag_access_id'), table_name='rag_access')
    op.drop_table('rag_access')
    op.drop_index(op.f('ix_rag_knowledge_bases_organization_id'), table_name='rag_knowledge_bases')
    op.drop_index(op.f('ix_rag_knowledge_bases_id'), table_name='rag_knowledge_bases')
    op.drop_table('rag_knowledge_bases')
    # ### end Alembic commands ###

