"""remove_unique_constraint_from_analysis_types_name

Revision ID: cee937ccf7b2
Revises: 2179ff480c0c
Create Date: 2025-11-24 05:51:08.537019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cee937ccf7b2'
down_revision = '2179ff480c0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_analysis_runs_tool_id', 'analysis_runs', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_runs', 'user_tools', ['tool_id'], ['id'])
    op.drop_index('name', table_name='analysis_types')
    op.alter_column('user_tools', 'tool_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('database', 'api', 'rag', name='tooltype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tools', 'tool_type',
               existing_type=sa.Enum('database', 'api', 'rag', name='tooltype'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)
    op.create_index('name', 'analysis_types', ['name'], unique=True)
    op.drop_constraint(None, 'analysis_runs', type_='foreignkey')
    op.create_foreign_key('fk_analysis_runs_tool_id', 'analysis_runs', 'user_tools', ['tool_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

